// 武神传说的数据库 by 苏轻

const skillData = {
    "基础技能" : [ // 颜色(白0绿1蓝2黄3紫4橙5红6)
        { name : "基本内功", color : 0, skid : "force", type1 : "0", type2 : "0" },
        { name : "基本轻功", color : 0, skid : "dodge", type1 : "0", type2 : "0" },
        { name : "基本拳脚", color : 0, skid : "unarmed", type1 : "0", type2 : "0" },
        { name : "基本招架", color : 0, skid : "parry", type1 : "0", type2 : "0" },
        { name : "基本刀法", color : 0, skid : "blade", type1 : "0", type2 : "0" },
        { name : "基本剑法", color : 0, skid : "sword", type1 : "0", type2 : "0" },
        { name : "基本棍法", color : 0, skid : "club", type1 : "0", type2 : "0" },
        { name : "基本杖法", color : 0, skid : "staff", type1 : "0", type2 : "0" },
        { name : "基本鞭法", color : 0, skid : "whip", type1 : "0", type2 : "0" },
        { name : "基本暗器", color : 0, skid : "throwing", type1 : "0", type2 : "0" },
    ],
    "武当派" : [
        { name : "梯云纵", color : 2, skid : "tiyunzong", type1 : "0", type2 : "0" },
        { name : "太极神功", color : 3, skid : "taijishengong", type1 : "0", type2 : "0" },
        { name : "太极拳", color : 3, skid : "taijiquan", type1 : "0", type2 : "0" },
        { name : "'太极剑法'", color : 4, skid : "taijijian", type1 : "0", type2 : "0" },
        { name : "太极拳_进阶", color : 4, skid : "taijiquan2", type1 : "拳脚", type2 : "招架" },
        { name : "梯云纵_进阶", color : 4, skid : "tiyunzong2", type1 : "轻功", type2 : "无" },
        { name : "太极剑法_进阶", color : 5, skid : "taijijian2", type1 : "无", type2 : "无" },
        { name : "先天太极_进阶", color : 5, skid : "taijishengong2", type1 : "无", type2 : "无" },
        { name : "武当心法", color : 1, skid : "wudangxinfa", type1 : "内功", type2 : "无" },
        { name : "武当剑法", color : 1, skid : "wudangjianfa", type1 : "武器", type2 : "无" },
        { name : "武当长拳", color : 1, skid : "wudangchangquan", type1 : "拳脚", type2 : "无" },
    ],
    "少林派" : [
        { name : "少林身法", color : 1, skid : "shaolinshenfa", type1 : "0", type2 : "0" },
        { name : "燃木刀法", color : 3, skid : "ranmudao", type1 : "0", type2 : "0" },
        { name : "一指禅", color : 3, skid : "yizhichan", type1 : "0", type2 : "0" },
        { name : "易筋经", color : 4, skid : "yijinjing", type1 : "0", type2 : "0" },
        { name : "一苇渡江_进阶", color : 4, skid : "shaolinshenfa2", type1 : "轻功", type2 : "无" },
        { name : "一指禅_进阶", color : 4, skid : "yizhichan2", type1 : "拳脚", type2 : "无" },
        { name : "燃木刀法_进阶", color : 5, skid : "ranmudao2", type1 : "无", type2 : "无" },
        { name : "金刚不坏体_进阶", color : 5, skid : "yijinjing2", type1 : "无", type2 : "无" },
        { name : "韦陀棍", color : 1, skid : "weituogun", type1 : "武器", type2 : "无" },
        { name : "混元一气", color : 1, skid : "hunyuanyiqi", type1 : "内功", type2 : "无" },
        { name : "伏虎拳", color : 1, skid : "fuhuquan", type1 : "拳脚", type2 : "无" },
        { name : "达摩剑", color : 2, skid : "damojian", type1 : "剑法", type2 : "无" },
        { name : "大力金刚拳", color : 2, skid : "jingangquan", type1 : "拳脚", type2 : "招架" },
    ],
    "华山派" : [
        { name : "劈石破玉拳", color : 1, skid : "poyuquan", type1 : "0", type2 : "0" },
        { name : "紫霞神功", color : 3, skid : "zixiashengong", type1 : "0", type2 : "0" },
        { name : "狂风快剑", color : 3, skid : "kuangfengkuaijian", type1 : "0", type2 : "0" },
        { name : "独孤九剑", color : 4, skid : "dugujiujian", type1 : "0", type2 : "0" },
        { name : "劈石破玉拳_进阶", color : 4, skid : "poyuquan2", type1 : "拳脚", type2 : "招架" },
        { name : "紫霞神功_进阶", color : 4, skid : "zixiashengong2", type1 : "内功", type2 : "无" },
        { name : "独孤九剑_进阶", color : 5, skid : "dugujiujian2", type1 : "无", type2 : "无" },
        { name : "狂风快剑_进阶", color : 5, skid : "kuangfengkuaijian2", type1 : "无", type2 : "无" },
        { name : "飞燕回翔", color : 1, skid : "feiyanhuixiang", type1 : "轻功", type2 : "无" },
        { name : "华山心法", color : 1, skid : "huashanxinfa", type1 : "内功", type2 : "无" },
        { name : "华山剑法", color : 1, skid : "huashanjianfa", type1 : "武器", type2 : "无" },
        { name : "华山拳法", color : 1, skid : "huashanquanfa", type1 : "拳脚", type2 : "无" },
    ],
    "峨眉派" : [
        { name : "诸天化身步", color : 1, skid : "zhutianbu", type1 : "0", type2 : "0" },
        { name : "临济十二庄", color : 3, skid : "linjizhuang", type1 : "0", type2 : "0" },
        { name : "九阴白骨爪", color : 3, skid : "jiuyinbaiguzhao", type1 : "0", type2 : "0" },
        { name : "倚天剑法", color : 4, skid : "yitianjianfa", type1 : "0", type2 : "0" },
        { name : "九阴白骨爪_进阶", color : 4, skid : "jiuyinbaiguzhao2", type1 : "拳脚", type2 : "招架" },
        { name : "诸天化身步_进阶", color : 4, skid : "zhutianbu2", type1 : "轻功", type2 : "无" },
        { name : "临济十二庄_进阶", color : 5, skid : "linjizhuang2", type1 : "无", type2 : "无" },
        { name : "倚天剑法_进阶", color : 5, skid : "yitianjianfa2", type1 : "无", type2 : "无" },
        { name : "峨眉心法", color : 1, skid : "emeixinfa", type1 : "内功", type2 : "无" },
        { name : "金顶绵掌", color : 1, skid : "jindingzhang", type1 : "拳脚", type2 : "招架" },
        { name : "回风拂柳剑", color : 2, skid : "huifengjian", type1 : "武器", type2 : "无" },
    ],
    "逍遥派" : [
        { name : "凌波微步", color : 3, skid : "lingboweibu", type1 : "0", type2 : "0" },
        { name : "北冥神功", color : 3, skid : "beimingshengong", type1 : "0", type2 : "0" },
        { name : "天山六阳掌", color : 3, skid : "liuyangzhang", type1 : "0", type2 : "0" },
        { name : "小无相功", color : 4, skid : "xiaowuxianggong", type1 : "0", type2 : "0" },
        { name : "北冥神功_进阶", color : 4, skid : "beimingshengong2", type1 : "内功", type2 : "招架" },
        { name : "天山六阳掌_进阶", color : 4, skid : "liuyangzhang2", type1 : "拳脚", type2 : "无" },
        { name : "凌波微步_进阶", color : 5, skid : "lingboweibu2", type1 : "无", type2 : "无" },
        { name : "小无相功_进阶", color : 5, skid : "xiaowuxianggong2", type1 : "无", type2 : "无" },
        { name : "如意刀", color : 1, skid : "ruyidao", type1 : "武器", type2 : "无" },
        { name : "逍遥心法", color : 1, skid : "xiaoyaoxinfa", type1 : "内功", type2 : "无" },
        { name : "天山折梅手", color : 2, skid : "zhemeishou", type1 : "拳脚", type2 : "招架" },
    ],
    "丐帮" : [
        { name : "逍遥游", color : 2, skid : "xiaoyaoyou", type1 : "0", type2 : "0" },
        { name : "打狗棒", color : 3, skid : "dagoubang", type1 : "0", type2 : "0" },
        { name : "混天气功", color : 3, skid : "huntianqigong", type1 : "0", type2 : "0" },
        { name : "降龙十八掌", color : 4, skid : "xianglongzhang", type1 : "0", type2 : "0" },
        { name : "混元天罡_进阶", color : 4, skid : "huntianqigong2", type1 : "内功", type2 : "无" },
        { name : "逍遥游_进阶", color : 4, skid : "xiaoyaoyou2", type1 : "轻功", type2 : "无" },
        { name : "打狗棒_进阶", color : 5, skid : "dagoubang2", type1 : "无", type2 : "无" },
        { name : "降龙十八掌_进阶", color : 5, skid : "xianglongzhang2", type1 : "无", type2 : "无" },
        { name : "叫花棒法", color : 1, skid : "jiaohuabangfa", type1 : "武器", type2 : "招架" },
        { name : "飞檐走壁", color : 1, skid : "feiyanzoubi", type1 : "轻功", type2 : "无" },
        { name : "丐帮心法", color : 1, skid : "gaibangxinfa", type1 : "内功", type2 : "无" },
        { name : "太祖长拳", color : 1, skid : "taizuchangquan", type1 : "拳脚", type2 : "无" },
    ],
    "杀手楼" : [
        { name : "穿心掌", color : 2, skid : "chuanxinzhang", type1 : "0", type2 : "0" },
        { name : "杀生决", color : 3, skid : "shashengjue", type1 : "0", type2 : "0" },
        { name : "踏雪寻梅", color : 3, skid : "taxuexunmei", type1 : "0", type2 : "0" },
        { name : "漫天花雨", color : 4, skid : "mantianhuayu", type1 : "0", type2 : "0" },
        { name : "穿心掌_进阶", color : 4, skid : "chuanxinzhang2", type1 : "拳脚", type2 : "招架" },
        { name : "杀生决_进阶", color : 4, skid : "shashengjue2", type1 : "内功", type2 : "无" },
        { name : "漫天花雨_进阶", color : 5, skid : "mantianhuayu2", type1 : "武器", type2 : "无" },
        { name : "踏雪寻梅_进阶", color : 5, skid : "taxuexunmei2", type1 : "轻功", type2 : "无" },
        { name : "飞刀", color : 1, skid : "feidao", type1 : "暗器", type2 : "无" },
        { name : "杀手步法", color : 1, skid : "shashoubufa", type1 : "轻功", type2 : "无" },
        { name : "杀手心法", color : 1, skid : "shashouxinfa", type1 : "内功", type2 : "无" },
    ],
    "内功" : [
        { name : "蛤蟆功", color : 4, skid : "hamagong", type1 : "内功", type2 : "拳脚" },
        { name : "化功大法", color : 4, skid : "huagongdafa", type1 : "内功", type2 : "无" },
        { name : "明玉功", color : 4, skid : "mingyugong", type1 : "内功", type2 : "轻功" },
        { name : "枯木神功", color : 4, skid : "kumushengong", type1 : "内功", type2 : "无" },
        { name : "神照经", color : 4, skid : "shenzhaojing", type1 : "内功", type2 : "拳脚" },
        { name : "血海魔功", color : 4, skid : "xuehaimogong", type1 : "内功", type2 : "无" },
        { name : "龙象般若功", color : 5, skid : "longxianggong", type1 : "内功", type2 : "无" },
        { name : "葵花神功", color : 5, skid : "kuihuashengong", type1 : "内功", type2 : "无" },
        { name : "不老长春功", color : 5, skid : "bahuanggong", type1 : "内功", type2 : "无" },
        { name : "九阳神功", color : 5, skid : "jiuyangshengong", type1 : "内功", type2 : "无" },
        { name : "九阴神功", color : 5, skid : "jiuyinshengong", type1 : "内功", type2 : "无" },
        { name : "太玄功", color : 5, skid : "taixuangong", type1 : "内功", type2 : "无" },
        { name : "密宗心法", color : 1, skid : "mizongxinfa", type1 : "内功", type2 : "无" },
        { name : "云龙心法", color : 1, skid : "yunlongxinfa", type1 : "内功", type2 : "无" },
        { name : "冷月神功", color : 1, skid : "lengyueshengong", type1 : "内功", type2 : "无" },
        { name : "神龙心法", color : 2, skid : "shenlongxinfa", type1 : "内功", type2 : "无" },
        { name : "五毒神功", color : 2, skid : "wudushengong", type1 : "内功", type2 : "无" },
        { name : "碧波神功", color : 2, skid : "biboshengong", type1 : "内功", type2 : "无" },
        { name : "白云心法", color : 3, skid : "baiyunxinfa", type1 : "内功", type2 : "无" },
        { name : "镇岳诀", color : 3, skid : "zhenyuejue", type1 : "内功", type2 : "无" },
        { name : "圣火神功", color : 3, skid : "shenghuoshengong", type1 : "内功", type2 : "无" },
    ],
    "轻功" : [
        { name : "神行百变", color : 2, skid : "shenxingbaibian", type1 : "轻功", type2 : "无" },
        { name : "踏歌行", color : 2, skid : "tagexing", type1 : "轻功", type2 : "无" },
        { name : "天南步", color : 2, skid : "tiannanbu", type1 : "轻功", type2 : "无" },
        { name : "金蛇游身步", color : 3, skid : "jinsheyoushenbu", type1 : "轻功", type2 : "无" },
        { name : "五毒烟萝步", color : 3, skid : "wuduyanluobu", type1 : "轻功", type2 : "无" },
        { name : "暗影浮香", color : 3, skid : "anyingfuxiang", type1 : "轻功", type2 : "无" },
        { name : "玄虚步", color : 4, skid : "xuanxubu", type1 : "轻功", type2 : "无" },
        { name : "意形步法", color : 1, skid : "yixingbufa", type1 : "轻功", type2 : "无" },
        { name : "云龙身法", color : 1, skid : "yunlongshenfa", type1 : "轻功", type2 : "无" },
        { name : "金雁功", color : 1, skid : "jinyangong", type1 : "轻功", type2 : "无" },
        { name : "四象步法", color : 2, skid : "sixiangbu", type1 : "轻功", type2 : "无" },
        { name : "恒山身法", color : 2, skid : "hengshanshenfa", type1 : "轻功", type2 : "无" },
        { name : "穿云纵", color : 2, skid : "chuanyunzong", type1 : "轻功", type2 : "无" },
        { name : "蟾蜍步法", color : 2, skid : "chanchubufa", type1 : "轻功", type2 : "无" },
        { name : "青蝠身法", color : 2, skid : "qingfushenfa", type1 : "轻功", type2 : "无" },
    ],
    "拳脚" : [
        { name : "鹰爪功", color : 2, skid : "yingzhuagong", type1 : "拳脚", type2 : "招架" },
        { name : "金蛇游身掌", color : 3, skid : "jinshezhang", type1 : "拳脚", type2 : "无" },
        { name : "大嵩阳神掌", color : 3, skid : "dasongyangshenzhang", type1 : "拳脚", type2 : "无" },
        { name : "七伤拳", color : 3, skid : "qishangquan", type1 : "拳脚", type2 : "招架" },
        { name : "三阴蜈蚣爪", color : 3, skid : "sanyinzhua", type1 : "拳脚", type2 : "招架" },
        { name : "弹指神通", color : 4, skid : "tanzhishengong", type1 : "拳脚", type2 : "无" },
        { name : "空明拳", color : 4, skid : "kongmingquan", type1 : "拳脚", type2 : "无" },
        { name : "参合指", color : 4, skid : "canhezhi", type1 : "拳脚", type2 : "无" },
        { name : "六脉神剑", color : 5, skid : "liumaishenjian", type1 : "无", type2 : "无" },
        { name : "黯然销魂掌", color : 5, skid : "anranxiaohun", type1 : "无", type2 : "无" },
        { name : "密宗大手印", color : 1, skid : "dashouyin", type1 : "拳脚", type2 : "无" },
        { name : "猴拳", color : 1, skid : "houquan", type1 : "拳脚", type2 : "无" },
        { name : "化骨绵掌", color : 2, skid : "huagumianzhang", type1 : "拳脚", type2 : "无" },
        { name : "八卦拳", color : 2, skid : "baguaquan", type1 : "拳脚", type2 : "无" },
        { name : "流云掌", color : 2, skid : "liuyunzhang", type1 : "拳脚", type2 : "无" },
        { name : "泰山拳法", color : 2, skid : "taishanquanfa", type1 : "拳脚", type2 : "招架" },
        { name : "绝情掌", color : 2, skid : "jueqingzhang", type1 : "拳脚", type2 : "无" },
        { name : "天长掌法", color : 3, skid : "tianchangzhang", type1 : "拳脚", type2 : "无" },
        { name : "摧心掌", color : 3, skid : "cuixinzhang", type1 : "拳脚", type2 : "无" },
    ],
    "招架" : [
        { name : "移花接木", color : 4, skid : "yihuajiemu", type1 : "招架", type2 : "无" },
        { name : "斗转星移", color : 5, skid : "douzhuanxingyi", type1 : "无", type2 : "无" },
        { name : "乾坤大挪移", color : 5, skid : "qiankundanuoyi", type1 : "无", type2 : "无" },
    ],
    "剑法" : [
        { name : "衡山五神剑", color : 3, skid : "hengshanwushenjian", type1 : "武器", type2 : "招架" },
        { name : "全真剑法", color : 3, skid : "quanzhenjianfa", type1 : "武器", type2 : "无" },
        { name : "辟邪剑法", color : 5, skid : "bixiejianfa", type1 : "无", type2 : "无" },
        { name : "玄铁剑法", color : 5, skid : "xuantiejianfa", type1 : "无", type2 : "无" },
        { name : "神龙剑", color : 1, skid : "shenlongjian", type1 : "武器", type2 : "无" },
        { name : "唐诗剑法", color : 1, skid : "tangshijianfa", type1 : "武器", type2 : "无" },
        { name : "云龙剑", color : 2, skid : "yunlongjian", type1 : "武器", type2 : "无" },
        { name : "圣火令法", color : 2, skid : "shenghuojianfa", type1 : "武器", type2 : "无" },
        { name : "金蛇剑法", color : 3, skid : "jinshejianfa", type1 : "武器", type2 : "无" },
        { name : "五毒钩法", color : 3, skid : "wudugoufa", type1 : "武器", type2 : "无" },
        { name : "恒山剑法", color : 3, skid : "hengshanjianfa", type1 : "武器", type2 : "无" },
        { name : "松风剑法", color : 3, skid : "songfengjianfa", type1 : "武器", type2 : "招架" },
        { name : "嵩山剑法", color : 3, skid : "songshanjianfa", type1 : "武器", type2 : "招架" },
        { name : "落英神剑", color : 3, skid : "luoyingshenjian", type1 : "武器", type2 : "无" },
        { name : "移风剑法", color : 3, skid : "yifengjian", type1 : "武器", type2 : "无" },
        { name : "天羽奇剑", color : 3, skid : "tianyuqijian", type1 : "武器", type2 : "无" },
    ],
    "刀法" : [
        { name : "五虎断门刀", color : 1, skid : "wuhuduanmendao", type1 : "武器", type2 : "无" },
        { name : "胡家刀法", color : 2, skid : "hujiadaofa", type1 : "武器", type2 : "招架" },
        { name : "狂风快刀", color : 3, skid : "kuangfengkuaidao", type1 : "武器", type2 : "无" },
        { name : "血刀", color : 5, skid : "xuedao", type1 : "无", type2 : "无" },
    ],
    "棍法" : [
        { name : "绝门棍", color : 1, skid : "juemengun", type1 : "武器", type2 : "轻功" },
        { name : "八卦棍法", color : 2, skid : "baguagun", type1 : "武器", type2 : "无" },
        { name : "中平枪法", color : 3, skid : "zhongpingqiang", type1 : "武器", type2 : "招架" },
        { name : "蒙古骑枪", color : 3, skid : "mengguqiqiang", type1 : "武器", type2 : "无" },
    ],
    "杖法" : [
        { name : "蛇岛奇功", color : 2, skid : "shedaoqigong", type1 : "武器", type2 : "招架" },
        { name : "灵蛇杖法", color : 4, skid : "lingshezhangfa", type1 : "武器", type2 : "招架" },
    ],
    "鞭法" : [
        { name : "云龙鞭法", color : 1, skid : "yunlongbian", type1 : "武器", type2 : "无" },
        { name : "秋风拂尘", color : 1, skid : "qiufengfuchen", type1 : "武器", type2 : "无" },
        { name : "银索金铃", color : 3, skid : "yinsuojinling", type1 : "武器", type2 : "无" },
    ],
    "暗器" : [
        { name : "金蛇锥法", color : 2, skid : "jinshezhui", type1 : "武器", type2 : "无" },
        { name : "飞星术", color : 2, skid : "feixingshu", type1 : "武器", type2 : "无" },
    ],
}


